### ISSUE TITLE
What consul versions does this tool support?

### ISSUE THREAD

**Issue by dschaaff** [hashicorp/consul-aws#3]
The readme states `This project is versioned separately from Consul. Supported Consul versions for each feature will be noted below. ` but I am unable to find a list of supported consul versions.

Is this documented anywhere?

**Comment by hanshasselberg** [comment]
Hi @dschaaff, sorry for the late response - I was somehow not subscribed to that project.
`consul-aws` is compatible with the current version and one version before. Right now that would be 1.4 and 1.3. That being said, only very basic functionality is used and it is possible that other versions work as well.
Small things in the UI - like the aws icon - will only be released as part of 1.4.1 and above.

**Comment by hanshasselberg** [comment]
I put a note in the readme: https://github.com/hashicorp/consul-aws/blob/master/README.md#compatibility-with-consul

**Comment by dschaaff** [comment]
Thanks!
