### ISSUE TITLE
[req] Publish docker images

### ISSUE THREAD

**Issue by dekimsey** [hashicorp/consul-aws#9]
This is a request to publish the tool to docker hub. I noticed in build-support there is already a Release.dockerfile, I was hoping there would be a corresponding image on docker hub.

I was able to build and run the Release dockerfile locally without trouble.

The only issue I had was because I was running in ECS/Fargate and I was running a sidecar consul container. In that environment one is unable to control task start-up ordering. It'd be helpful if the `fetchIndefinitely` [method](https://github.com/hashicorp/consul-aws/blob/master/catalog/consul.go#L267) would wait longer than a couple of seconds.  I had to wrap my docker command into a shell script to make it work reliably:

```
sh -c "until nc -z localhost:8500; do sleep 1; echo Waiting for consul to come up...; done; exec consul-aws sync-catalog -to-consul -to-aws -aws-namespace-id $namespace_id"
```

**Comment by hanshasselberg** [comment]
Good point @dekimsey! There is no docker image yet, but we certainly should have one!
